before:
  hooks:
    - go generate ./...
    - chmod +x upx.sh
    - chmod +x upx.upgrade.sh
    - cp example.yaml shuttle.yaml
project_name: shuttle
builds:
- main: cmd/main.go
  env:
    - CGO_ENABLED=1
    - CC=arm-linux-gnueabi-gcc
  ldflags:
    - "-s -w"
  binary: shuttle
  flags:
    - -tags=release
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - 6
    - 7
  hooks:
    post: ./upx.sh
  ignore:
    - goos: freebsd
      goarch: arm
      goarm: 6
    - goos: freebsd
      goarch: arm
      goarm: 7
    - goos: openbsd
      goarch: arm
      goarm: 6
    - goos: openbsd
      goarch: arm
      goarm: 7
- main: scripts/upgrade.go
  env:
    - CGO_ENABLED=0
  ldflags:
    - "-s -w"
  binary: upgrade
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  hooks:
    post: ./upx.upgrade.sh
  ignore:
    - goos: freebsd
      goarch: arm
      goarm: 6
    - goos: freebsd
      goarch: arm
      goarm: 7
    - goos: openbsd
      goarch: arm
      goarm: 6
    - goos: openbsd
      goarch: arm
      goarm: 7
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^tests'
      - Merge pull request
      - Merge branch
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}_v{{ .Arm }}{{ end }}'
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - shuttle.yaml
    - start.sh
    - start.bat
  wrap_in_directory: true
  replacements:
    amd64: 64-bit
    386: 32-bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
release:
  github:
    owner: cxjava
    name: shuttle
  draft: true
  prerelease: true
  name_template: "{{.ProjectName}}-v{{.Version}}-{{.ShortCommit}}"
