before:
  hooks:
    - go generate ./...
project_name: shuttle
builds:
- main: cmd/main.go
  env:
    - CGO_ENABLED=0
    - GIN_MODE=release
  ldflags:
    - "-s -w"
  binary: shuttle
  goos:
    - windows
    - darwin
    - linux
    - freebsd
    - openbsd
    - netbsd
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  hooks:
    post: find ./ -xdev -maxdepth 3 -type f -name 'shuttle*' | xargs upx
  ignore:
    - goos: freebsd
      goarch: arm
      goarm: 6
    - goos: freebsd
      goarch: arm
      goarm: 7
    - goos: openbsd
      goarch: arm
      goarm: 6
    - goos: openbsd
      goarch: arm
      goarm: 7
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^tests'
      - Merge pull request
      - Merge branch
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}_v{{ .Arm }}{{ end }}'
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - GeoLite2-Country.mmdb
    - shuttle.yaml
    - RespFiles/*
    - view/**/*
  wrap_in_directory: true
  replacements:
    amd64: 64-bit
    386: 32-bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
release:
  github:
    owner: cxjava
    name: shuttle
  draft: true
  prerelease: true
  name_template: "{{.ProjectName}}-v{{.Version}}-{{.ShortCommit}}"
