language: go

dist: xenial
sudo: true

go:
- 1.11.x

cache: apt

addons:
  apt:
    packages:
      - rpm
      - upx

env:
  - GORELEASER_VERSION=0.93.2

matrix:
  include:
  - name: goreleaser
    go: "1.11.x"
    script:
      - wget https://github.com/goreleaser/goreleaser/releases/download/v${GORELEASER_VERSION}/goreleaser_amd64.deb
      - sudo dpkg -i goreleaser_amd64.deb
      - rm goreleaser_amd64.deb
      - cp example.yaml shuttle.yaml
      - mkdir RespFiles
      - goreleaser --skip-validate --skip-sign --debug
