language: go

dist: xenial
sudo: true

go:
- 1.11.x

cache: apt

env:
  global:
    - GORELEASER_VERSION=0.93.2
    - UPXVER="3.95"

matrix:
  include:
  - name: goreleaser
    go: "1.11.x"
    before_script:
      - go get -u -v github.com/UnnoTed/fileb0x
      - go install github.com/UnnoTed/fileb0x
      - go generate ./...
  
    script:
      - wget https://github.com/goreleaser/goreleaser/releases/download/v${GORELEASER_VERSION}/goreleaser_amd64.deb
      - sudo dpkg -i goreleaser_amd64.deb
      - rm goreleaser_amd64.deb
      - |
        if [[ ! -f "upx/${UPXVER}/upx" ]]
        then
          echo "Installing upx .."
          curl -OL "https://github.com/upx/upx/releases/download/v${UPXVER}/upx-${UPXVER}-amd64_linux.tar.xz"
          tar xvf "upx-${UPXVER}-amd64_linux.tar.xz"
          mkdir -p upx
          mv "upx-${UPXVER}-amd64_linux" "upx/${UPXVER}"
        fi
      - export PATH="${TRAVIS_BUILD_DIR}/upx/${UPXVER}/:${PATH}"
      - upx --version | grep -E '^upx'
      - cp example.yaml shuttle.yaml
      - echo '#!/bin/bash' >> upx.sh
      - echo "find ./dist -xdev -maxdepth 3 -type f -name 'shuttle*' | xargs upx" >> upx.sh
      - chmod +x upx.sh
      - cat upx.sh
      - goreleaser --skip-validate --skip-sign --debug
